# Generated by Django 2.2.28 on 2022-09-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='highest_sector',
            field=models.IntegerField(default=1),
        ),
    ]
