# Generated by Django 2.2.28 on 2022-09-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220913_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_updated',
            field=models.DateTimeField(blank=True),
        ),
    ]
