# Generated by Django 2.2.28 on 2022-09-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220913_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='details2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
