# Generated by Django 2.2.28 on 2022-09-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_activity_details2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
