# Generated by Django 2.2.28 on 2022-09-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_player_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('SectorCleared', 'SectorCleared'), ('RecipeUnlock', 'RecipeUnlock'), ('ModuleUnlock', 'ModuleUnlock'), ('AchievementComplete', 'AchievementComplete'), ('ResearchComplete', 'ResearchComplete'), ('Unlock', 'Unlock'), ('AIUpgrade', 'AIUpgrade'), ('GameOpened', 'GameOpened'), ('ShardCompleted', 'ShardCompleted'), ('InfiniteResource', 'InfiniteResource')], max_length=50),
        ),
    ]
