# Generated by Django 3.2.15 on 2022-09-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
