# Generated by Django 3.2.15 on 2022-09-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220925_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('SectorCleared', 'SectorCleared'), ('RecipeUnlock', 'RecipeUnlock'), ('ModuleUnlock', 'ModuleUnlock'), ('AchievementComplete', 'AchievementComplete'), ('ResearchComplete', 'ResearchComplete'), ('Unlock', 'Unlock'), ('AIUpgrade', 'AIUpgrade'), ('GameOpened', 'GameOpened'), ('ShardCompleted', 'ShardCompleted'), ('InfiniteResource', 'InfiniteResource'), ('PrestigeReset', 'PrestigeReset'), ('RedeemCode', 'RedeemCode')], max_length=50),
        ),
    ]
