# Generated by Django 3.2.15 on 2022-10-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save', models.TextField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
            ],
        ),
    ]
