# Generated by Django 3.2.15 on 2022-10-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cloudsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsave',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
