# Generated by Django 3.2.15 on 2022-10-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cloudsave_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudsave',
            old_name='save',
            new_name='save_data',
        ),
    ]
