# Generated by Django 3.2.15 on 2022-10-26 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_rename_save_cloudsave_save_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloudSave',
            new_name='CloudSaveOLD',
        ),
        migrations.AddField(
            model_name='player',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
